#!/usr/bin/env python3
# -*- encoding: utf-8; py-indent-offset: 4 -*-
import shlex

def agent_fritzbox_smarthome_arguments(params, hostname, ipaddress):
    args = shlex.quote(ipaddress)
    args += " " + shlex.quote(params["username"])
    args += " " + shlex.quote(params["password"])

    if "port" in params:
        args += " --port " + str(params["port"])

    if "protocol" in params:
        if str(params["protocol"]) == '1':
            args += " --protocol https"
        else:
            args += " --protocol http"

    if "ssl" in params:
        args += " --ignore_ssl"

    return args

special_agent_info['fritzbox_smarthome'] = agent_fritzbox_smarthome_arguments
