#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def agent_fritzbox_smarthome_arguments(params, hostname, ipaddress):
    args = quote_shell_string(ipaddress)
    if "username" in params:
        args += " --username " + quote_shell_string(params["username"])
    if "password" in params:
        args += " --password " + quote_shell_string(params["password"])
    if "port" in params:
        args += " --port " + str(params["port"])

    if "protocol" in params:
        if str(params["protocol"]) == '1':
            args += " --protocol https"
        else:
            args += " --protocol http"

    if "ssl" in params:
        args += " --ignore_ssl"

    return args

special_agent_info['fritzbox_smarthome'] = agent_fritzbox_smarthome_arguments